### ISSUE TITLE
Sort files/folders

### ISSUE THREAD

**Issue by vvos** [Dis3buted/OutlineView#2]
Hello,

This is not an issue for me anymore but I did not know how to contact you.

If you put this on line 37 of FileItem.swift before the 'return files' it will sort everything ascending including subfolders and files. 

`files.sort { $0.url.lastPathComponent.compare(
                $1.url.lastPathComponent, options:  String.CompareOptions.literal ) == .orderedAscending
            }`

**Comment by Dis3buted** [comment]
okay
